# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 07:14
from __future__ import unicode_literals

from typing import List  # noqa

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: List[str]

    operations = [
        migrations.CreateModel(
            name="Checkpoint",
            fields=[
                ("key", models.CharField(max_length=256, primary_key=True, serialize=False)),
                ("checkpoints", models.TextField()),
            ],
        ),
    ]
